### ISSUE TITLE
Fee sharing UI implementation for staking page

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/governance-dapp#100]
Contracts:

testnet: 0x740E6f892C0132D659Abcd2B6146D237A4B6b653
mainnet: 0x12B1B0C67d9A771EB5Db7726d23fdc6848fd93ef

Code: https://github.com/DistributedCollective/Sovryn-smart-contracts/blob/development/contracts/governance/FeeSharingProxy.sol

Abi: https://discord.com/channels/729675474665603133/762597737388310538/838714035834847243

**Comment by t-z-u** [comment]
Currently working on the design for this
