### ISSUE TITLE
Fee sharing for vesting contracts

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/governance-dapp#117]
**!!Do not work on this task until July or James says it's ok now, contract may change.**

Currently fee sharing is only checking for collected fees for user stake but should also check in all of vesting contracts too, withdrawals also should be done for each vesting contract (if contracts will not be changed to collect everything in one call).

**Comment by t-z-u** [comment]
update, the contract is still being changed in order - tyrone will know the status of this
