### ISSUE TITLE
Proposals not loading in bitocracy page

### ISSUE THREAD

**Issue by TheSovrynGimp** [DistributedCollective/governance-dapp#120]
Going to load a proposal in the Bitocracy page https://bitocracy.sovryn.app/ by clicking the 'View Proposal' button on any of the current proposals results in endless loading. 

Multiple users have already tried clearing cache, refreshing browser, differnet browsers etc.

![image](https://user-images.githubusercontent.com/86018066/122269837-8fbfce00-ced5-11eb-8eb7-231191320f22.png)

**Comment by tiltom** [comment]
Listings loading was solved in https://github.com/DistributedCollective/governance-dapp/pull/121 but the detail is still too slow, I will try to solve that in another PR.
