### ISSUE TITLE
Cannot see full vote balance or proposer address in UI

### ISSUE THREAD

**Issue by john-light** [DistributedCollective/governance-dapp#20]
Currently the Proposer Address and vote balances are truncated in the UI. For clarity and ease of copying I would like to be able to see the full, unabbreviated address/number.

![Screenshot_2021-02-19 SOVRYN Bitocracy Sovryn Bitocracy(6)](https://user-images.githubusercontent.com/9424721/108561731-bb86ca80-72cc-11eb-9e2d-84170237b466.png)

![Screenshot_2021-02-19 SOVRYN Bitocracy Sovryn Bitocracy(2)](https://user-images.githubusercontent.com/9424721/108561104-af4e3d80-72cb-11eb-9f14-bc327c957ef1.png)

![Screenshot_2021-02-19 SOVRYN Bitocracy Sovryn Bitocracy(3)](https://user-images.githubusercontent.com/9424721/108561108-b07f6a80-72cb-11eb-87f8-024300511d64.png)

**Comment by creed-victor** [comment]
Addresses and vote amounts may be very long and break design so I wouldn't dare to show entire value, however adding copy button near addresses and maybe tooltip with real amount for tooltips would help to solve this.

**Comment by john-light** [comment]
@creed-victor maybe we could use something like the [IdentityBadge](https://ui.aragon.org/identity-badge/) in aragonUI for this?

**Comment by creed-victor** [comment]
Yes, component like this would be useful
