### ISSUE TITLE
Vote outcome could be more explicit

### ISSUE THREAD

**Issue by john-light** [DistributedCollective/governance-dapp#21]
While there are some color cues suggesting what the outcome might be, I think it would help with clarity if the outcomes had explicit labels "Yes"/"No" or "Approve"/"Reject".

![Screenshot_2021-02-19 SOVRYN Bitocracy Sovryn Bitocracy(4)](https://user-images.githubusercontent.com/9424721/108561361-1f5cc380-72cc-11eb-96ff-04b276dafb48.png)

![Screenshot_2021-02-19 SOVRYN Bitocracy Sovryn Bitocracy(5)](https://user-images.githubusercontent.com/9424721/108561432-41eedc80-72cc-11eb-95ce-eceed2487174.png)

**Comment by creed-victor** [comment]
@t-z-u

**Comment by t-z-u** [comment]
@creed-victor how do we put this into a list to come back to after priorities have been finished?

**Comment by t-z-u** [comment]
on trello I would make another column and put these in it
