### ISSUE TITLE
Cannot tell current outcome and outcome necessary for a proposal to pass

### ISSUE THREAD

**Issue by john-light** [DistributedCollective/governance-dapp#22]
No information is shown regarding whether or not a proposal will pass given the current vote weighting, nor what the actual parameters are required for a vote to pass.

![Screenshot_2021-02-19 SOVRYN Bitocracy Sovryn Bitocracy(7)](https://user-images.githubusercontent.com/9424721/108575417-2abde800-72e8-11eb-83c6-6b3bd48f32df.png)

It would be nice to see:
1. Current outcome
2. Quorum required
3. Support required

See for example how this information is communicated in the [Aragon Voting](https://rinkeby.client.aragon.org/#/camino/0xaaed9220353c1d3319adafb3d377cde54fa2e46e/vote/1/) app:

![ara-vote](https://user-images.githubusercontent.com/9424721/108575855-948ac180-72e9-11eb-94c4-4d9502224c4a.png)

**Comment by creed-victor** [comment]
@t-z-u

**Comment by t-z-u** [comment]
@creed-victor how do we put this into a list to come back to after priorities have been finished?
