### ISSUE TITLE
"Sovryn" is capitalized

### ISSUE THREAD

**Issue by john-light** [DistributedCollective/governance-dapp#27]
Currently in the interface the word "Sovryn" is in all caps. However in most other instances of the word Sovryn appearing on the Sovryn website (other than the stylized Sovryn logo and "comic book" style graphic text) the word Sovryn is title-cased. For consistency's sake, we should have the name title-cased as "Sovryn" in the governance dapp as well.

![Screenshot_2021-02-25 SOVRYN Bitocracy Sovryn Bitocracy(1)](https://user-images.githubusercontent.com/9424721/109112232-45d59100-7708-11eb-99ca-a513c2aad519.png)

Edit: I would have made a PR to suggest this change but I could not find the text to edit when I searched this repository for "SOVRYN Bitocracy" (the text I want to change). Any idea why I couldn't find that text here, even though it shows up in the governance dapp on the website?

**Comment by creed-victor** [comment]
> Currently in the interface the word "Sovryn" is in all caps. However in most other instances of the word Sovryn appearing on the Sovryn website (other than the stylized Sovryn logo and "comic book" style graphic text) the word Sovryn is title-cased. For consistency's sake, we should have the name title-cased as "Sovryn" in the governance dapp as well.

@t-z-u, that's for you to decide and approve

> I would have made a PR to suggest this change but I could not find the text to edit when I searched this repository for "SOVRYN Bitocracy" (the text I want to change). Any idea why I couldn't find that text here, even though it shows up in the governance dapp on the website?

Most likely that's because search happening for default `development` branch (vote.sovryn.app) and bitocracy code is in `bitocracy` branch.

**Comment by t-z-u** [comment]
@creed-victor how do we put this into a list to come back to after priorities have been finished?

**Comment by creed-victor** [comment]
> @creed-victor how do we put this into a list to come back to after priorities have been finished?

I can create new label for that and tag it
