### ISSUE TITLE
Address link is shown in Tx Hash column

### ISSUE THREAD

**Issue by john-light** [DistributedCollective/governance-dapp#29]
See how the Tx Hash shows the same link as the Addresses column:

![Screenshot_2021-02-25 SOVRYN Bitocracy Sovryn Bitocracy(2)](https://user-images.githubusercontent.com/9424721/109231393-811da180-7794-11eb-8bdb-abadc7b79602.png)

**Comment by creed-victor** [comment]
@pietro-maximoff, I think event returns transactionHash, if not - just remove that column

**Comment by pietro-maximoff** [comment]
> @pietro-maximoff, I think event returns transactionHash, if not - just remove that column

ok
