### ISSUE TITLE
0 voting power votes shown

### ISSUE THREAD

**Issue by john-light** [DistributedCollective/governance-dapp#30]
On this proposal: https://bitocracy.sovryn.app/proposals/3/governorOwner

You can see a vote that is shown with 0 voting power:

![Screenshot_2021-02-25 SOVRYN Bitocracy Sovryn Bitocracy(3)](https://user-images.githubusercontent.com/9424721/109231921-5aac3600-7795-11eb-8697-7808dec35b0b.png)

Could we make it so that 0 voting power transactions are rejected rather than shown in the list with 0 voting power? It just seems odd to me to include votes that aren't valid.

**Comment by creed-victor** [comment]
Rejecting should be done in smart-contract side. We can filter out voters with 0 voting power but it needs to be decided if we want to do it - maybe it's useful to see zeros to know overall interest for proposal to pass/be defeated.
