### ISSUE TITLE
Bitocracy Voting Power and other proposal details.

### ISSUE THREAD

**Issue by powerhousefrank** [DistributedCollective/governance-dapp#34]
**Is your feature request related to a problem? Please describe.**
Currently, there is no simple way to create a proposal, also no way to know how much is the quorum votes and the proposal threshold (The minimum amount of voting power required for making a proposal). A simple interface to view these, along with how the total voting power is calculated based on the staked amount and schedule would be a nice addition.

**Describe the solution you'd like**
A simple interface to see the above-mentioned values and the staking power based on the address linked through the wallet, or by an address input.

**Additional context**
This is just a suggestion and I believe a bit more discussion regarding this will be nice to finalize the work to be done.

**Comment by creed-victor** [comment]
So,
- dapp should have a button "Propose"  in main page (proposals page)
- "Propose" button is disabled by default and enabled only for connected users who has enough voting power. (voting power required can received by calling proposalThreshold method on Governor contract)
- clicking "Propose" button would open new page (or maybe modal) with form for filling in.
- Form should have:
  - description field (string)
  - up to 10 rows of following fields: targets (string/address), values (number), signatures (string), calldatas (string).
     I think there should be + and - buttons so user would be able to add or remove new row.
     At least one row must be filled.

Method to create proposal:

https://github.com/DistributedCollective/governance-dapp/blob/7f0e7a45cc08b88969b4adab751fa13ae0516285/src/app/containers/BlockChainProvider/requests/governance.ts#L3-L20

Contract solidy code: 
https://github.com/DistributedCollective/Sovryn-smart-contracts/blob/6685cf7056d56414989ce5293ff8732d20f00f61/contracts/governance/GovernorAlpha.sol#L169-L175

**Comment by creed-victor** [comment]
Deployed to testnet.

**Comment by powerhousefrank** [comment]
What is the current testnet address of the Bitocracy website?
