### ISSUE TITLE
Proposal voting dialog doesn't allow use of browser scroll bar

### ISSUE THREAD

**Issue by soulBit** [DistributedCollective/governance-dapp#42]
User reported that the same problem is happening on Bitocracy app as in DistributedCollective/Sovryn-frontend/issues/442:

https://github.com/DistributedCollective/Sovryn-frontend/issues/442#issuecomment-796778952
![image](https://user-images.githubusercontent.com/765825/110832552-5a329580-8293-11eb-9317-7bccf848a7e3.png)

Same fix should apply.

**Comment by pietro-maximoff** [comment]
fixed here #452
