### ISSUE TITLE
Enable testing Bitocracy on testnet

### ISSUE THREAD

**Issue by john-light** [DistributedCollective/governance-dapp#43]
On https://bitocracy.sovryn.app it is not possible to use with RSK testnet:

![bitocracy-testnet](https://user-images.githubusercontent.com/9424721/111050828-e91ee980-841c-11eb-8e71-5a88f0f2da85.png)

**Comment by powerhousefrank** [comment]
This is the old one: https://bitocracy-dapp-git-feat-18-multiple-governance-contracts-sovryn.vercel.app/

I will ask for the updated one to be posted here.

**Comment by creed-victor** [comment]
Will setup https://bitocracy.test.sovryn.app for this later

**Comment by creed-victor** [comment]
Testnet is now available at https://bitocracy.test.sovryn.app

**Comment by john-light** [comment]
Very helpful, thank you @creed-victor!
