### ISSUE TITLE
Wrong unlock date shown

### ISSUE THREAD

**Issue by john-light** [DistributedCollective/governance-dapp#53]
On the "Stake SOV" modal I selected July 31 as the end of my staking duration, however once I confirmed the tx it shows July 17 as my "unlock date". Seems like an "off by one" error or something - is this a mistake or no?

URL: https://bitocracy.test.sovryn.app/

txid: https://explorer.testnet.rsk.co/tx/0xa41f7397a2bad3cc59ecb7f4242f61c8690f8ce259a9411d4972596189b6419a

![select-unstake-date](https://user-images.githubusercontent.com/9424721/112366987-c5c32c80-8caf-11eb-8714-41ad468a2f63.png)

![off-by-one](https://user-images.githubusercontent.com/9424721/112367007-cb207700-8caf-11eb-86c1-33361eb650d0.png)

**Comment by jjmr007** [comment]
Hello Light... can you please share your transaction Id?... It is just to discard if it is a smart contract problem or a front end problem.

**Comment by pietro-maximoff** [comment]
i did the same and everything is good - https://prnt.sc/10uughk

**Comment by john-light** [comment]
@jjmr007 I added more info including txid to the issue above

**Comment by john-light** [comment]
Just tried again and did not get the same issue, will close this for now.
